apiVersion: apps/v1
kind: Deployment # sample deployment
metadata:
  name: my-nginx
spec:
  replicas: 3 # kla-set: {{.replicas}}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "nginx:1.23" # kla-set: {{.image}}:{{.tag}}
        ports:
        - protocol: TCP
          containerPort: 80
